name = "FactoJulia"
uuid = "dfb28f7d-13ec-4d45-80b3-794598a53597"
version = "1.0.0-DEV"
authors = ["Adrien Sli <adrien.slifirski@gmail.com>", "Stave Icnel Dany OSIAS <osias.stave@outlook.com>", "and Contributors"]

[deps]
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[compat]
Bonito = "4.1.11"
CSV = "0.10.15"
DataFrames = "1.8.1"
Dates = "1.11.0"
LinearAlgebra = "1.12.0"
Makie = "0.24.6"
MultivariateStats = "0.10.3"
Plots = "1.41"
Printf = "1.11.0"
Revise = "3.12.1"
SharedArrays = "1.11.0"
Statistics = "1.11.1"
WGLMakie = "0.13.6"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
