name = "FactoJulia"
uuid = "dfb28f7d-13ec-4d45-80b3-794598a53597"
version = "1.0.0-DEV"
authors = ["Adrien-Sli <adrien.slifirski@gmail.com> and contributors"]

[deps]
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[compat]
Bonito = "4.1.7"
GeometryBasics = "0.5.10"
Makie = "0.24.6"
WGLMakie = "0.13.6"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
