name = "FactoJulia"
uuid = "dfb28f7d-13ec-4d45-80b3-794598a53597"
version = "1.0.0-DEV"
authors = [
    "Adrien Sli <adrien.slifirski@gmail.com>",
    "Stave Icnel Dany OSIAS <osias.stave@outlook.com>",
    "and Contributors"
]


[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
LinearAlgebra = "1.12.0"
Statistics = "1.11.1"
Plots = "1.42.0"
Makie = "0.24.6"
WGLMakie = "0.13.6"
MultivariateStats = "0.10.3"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
